export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  KETUA: 'ketua',
  WAKIL_KETUA: 'wakil_ketua',
  BENDAHARA: 'bendahara',
  SEKRETARIS: 'sekretaris',
  HUMAS: 'humas', // New Role
  ANGGOTA: 'anggota',
  CONTENT_CREATOR: 'content_creator',
};

export const PERMISSIONS = {
  // General
  VIEW_DASHBOARD: 'view_dashboard',

  // Members
  MANAGE_MEMBERS: 'manage_members', // Create, Update, Delete, Approve
  VIEW_MEMBERS: 'view_members',
  APPROVE_USERS: 'approve_users',

  // Finance
  MANAGE_FINANCE: 'manage_finance',
  VIEW_FINANCE: 'view_finance',
  EXPORT_FINANCE: 'export_finance',

  // Activities
  MANAGE_ACTIVITIES: 'manage_activities',
  APPROVE_ACTIVITIES: 'approve_activities',
  VIEW_ACTIVITIES: 'view_activities',
  PROPOSE_ACTIVITY: 'propose_activity',

  // Announcements
  MANAGE_ANNOUNCEMENTS: 'manage_announcements',

  // Gallery
  MANAGE_GALLERY: 'manage_gallery',

  // Hero Carousel
  MANAGE_HERO: 'manage_hero',

  // System
  MANAGE_ROLES: 'manage_roles',
  VIEW_LOGS: 'view_logs',

  // Modules (New)
  MANAGE_CORRESPONDENCE: 'manage_correspondence', // Surat
  MANAGE_INVENTORY: 'manage_inventory', // Inventaris
  MANAGE_PARTNERS: 'manage_partners', // Kemitraan
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.KETUA]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.APPROVE_USERS,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.APPROVE_ACTIVITIES,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.MANAGE_HERO,
    PERMISSIONS.VIEW_LOGS,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.MANAGE_CORRESPONDENCE,
    PERMISSIONS.MANAGE_PARTNERS,
  ],

  [ROLES.WAKIL_KETUA]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.APPROVE_USERS,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.APPROVE_ACTIVITIES,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.MANAGE_HERO,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.MANAGE_INVENTORY,
  ],

  [ROLES.BENDAHARA]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.MANAGE_FINANCE,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.EXPORT_FINANCE,
    PERMISSIONS.VIEW_ACTIVITIES,
  ],

  [ROLES.SEKRETARIS]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_MEMBERS,
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.MANAGE_ACTIVITIES,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.MANAGE_GALLERY,
    PERMISSIONS.MANAGE_CORRESPONDENCE, // Key role for Surat
    PERMISSIONS.MANAGE_INVENTORY,
  ],

  [ROLES.HUMAS]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.MANAGE_PARTNERS, // Key role for Kemitraan
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
  ],

  [ROLES.CONTENT_CREATOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.MANAGE_GALLERY,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.PROPOSE_ACTIVITY,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
  ],

  [ROLES.ANGGOTA]: [
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.PROPOSE_ACTIVITY,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
  ],
};

export const hasPermission = (userRole, permission) => {
  if (!userRole) return false;
  const permissions = ROLE_PERMISSIONS[userRole] || [];
  return permissions.includes(permission);
};
